server {
    listen       8080;
    server_name  localhost;

    location / {
        root   /opt/app-root/src;
        index  index.html;
        try_files $uri $uri/ =404;
    }

    error_page 404 /index.html;
    location = /index.html {
        root /opt/app-root/src;
    }
}
